### PR TITLE
Feature/#19 electricity import limit

### LINKED ISSUE #19: limited electricity imports from national system constraint
Add a custom constraint limiting the annual imported electricity

### PR DESCRIPTION
**Pull request by gplssm**
Fix #19 

### Things, not so perfect

- `imported_electricity_limit()` is called in `smulate()`. Is necessary because the `solph.Model()` instance is required to select respective flows
- Selection of flows is label-based -> easy to break

### CODE REVIEW

**Comment by gplssm** [comment]
### Things done

-  Additional constraint is added and called after operational model is created
- Scenario file "sq" and "NEP2035" are equipped with additional parameter `limit`in "external_grid"
- Checked if constraints appears in .lp file
- Tested computability on very small model

### Remaining issues/todos

- [ ] `flex_cen` does not appear in .lp file in NEP2035 scenario
- [ ] `imported_electricity_limit()` is called in `simulate()`. Is necessary because the `solph.Model()` instance is required to select respective flows. Either leave it like this or move `om = solph.Model(esys)` to `create_oemof_model()`

**Comment by gplssm** [comment]
> I found 1 bug: You have 2 node prefixes in the `el_demand_labels`.

What does this mean? And did you fix it?

> As you did check the LP file, I checked the actual results.
> 
> **Example:**
> NEP2035
> import limit=0.01
> 2015-06-01 00:00:00 _to_ 2015-06-07 23:00:00'
> **Results:**
> EL DEMAND: 186371
> EL IMPORT: 1884 **(~1 % of demand -> OK)**
> 
> I varied the import limit and it seems to work as expected.

Hmm :thinking: this is actually not ok. The constraints says it must be less or equal to 1 % and the results show it's slightly above.
The question is: did you calculate EL DEMAND in exactly the same way as in the constraint?

**Comment by nesnoj** [comment]
I overlooked your 2nd post before. I've finished 2+3.
For 1.: I can see `flex_cen` in my lp file...

**Comment by nesnoj** [comment]
> What does this mean? And did you fix it?

Yepp, it involved "trans_dummy_th_dec_pth" and was removed anyway. All good.

> Hmm  this is actually not ok. The constraints says it must be less or equal to 1 % and the results show it's slightly above.
> The question is: did you calculate EL DEMAND in exactly the same way as in the constraint?

You're right, it's slightly more than 1%. I did it the same way as in the constraint and rechecked the code again. I thought this might be due to rounding errors somewhere?! I cannot see what's wrong :(

If you wanna check it out, you can find it in a new branch [here](https://github.com/windnode/WindNODE_ABW/blob/feature/%2319-electricity-import-limit-validation/windnode_abw/tools/draw.py#L186-L213))
Recent working dump is located [here](https://next.rl-institut.de/s/PnX5ZkLY8Y7gE44)

My results for this configuration:
```
=====================================================
EL DEMAND:  186326.52743953135
EL IMPORT:  1883.5919631873612
SHARE:  1.0109091759887192  %
=====================================================
```

**Pull request merged**
