### PR TITLE
Feature/#78 display notebooks in docs

### LINKED ISSUE #78: include notebooks into RTD documentation
The Sphinx extension [nbsphinx](https://nbsphinx.readthedocs.io) integrates notebooks in Sphinx docs. The normal workflow includes execution of a notebook. Because this takes too long for all scenarios of WindNODE_ABW, it is not an option. Execution can be bypassed and notebooks can rendered from executed notebooks.
As the size and number of notebooks and changes made to these would grow the size of the repo, @nesnoj and I decided not to commit executed notebooks to this repo.
Instead, we are thinking of creating a separate repo to only store executed notebooks. Git tags could help to manage versions.

Btw, Binder is not really an option because of computational limitations and the need to store the results data somewhere publicly accessible.

Tasks

- [x] Check how notebooks from external sources can be included, i.e. [nbsphinx-link](https://github.com/vidartf/nbsphinx-link) **We do it differently**
- [x]  Check if (even anonymous) [gists](https://pypi.org/project/python-gist/) are a good alternative to a github repo
- [x] May it is an option to convert notebooks to `.rst` and render from there via [sphinx include](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include) **NOT**

### LINKED ISSUE #125: ImportError: pyutilib.enum has been removed.
Somehow, installing windnode-abw on the SRVSIM01 leads to an import error. Traceback

```
Traceback (most recent call last):
  File "run_scenario.py", line 11, in <module>
    from windnode_abw.model import Region
  File "/home/local/RL-INSTITUT/guido.plessmann/git-repos/WindNODE_ABW/windnode_abw/model/__init__.py", line 10, in <module>
    from windnode_abw.model.region.tools import \
  File "/home/local/RL-INSTITUT/guido.plessmann/git-repos/WindNODE_ABW/windnode_abw/model/region/tools.py", line 10, in <module>
    import oemof.solph as solph
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/oemof/solph/__init__.py", line 1, in <module>
    from oemof.solph.network import (Sink, Source, Transformer, Bus, Flow,
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/oemof/solph/network.py", line 20, in <module>
    from oemof.solph import blocks
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/oemof/solph/blocks.py", line 13, in <module>
    from pyomo.core import (Var, Set, Constraint, BuildAction, Expression,
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyomo/core/__init__.py", line 11, in <module>
    from pyomo.core.expr import *
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyomo/core/expr/__init__.py", line 36, in <module>
    from .calculus.derivatives import differentiate
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in <module>
    from pyutilib.enum import Enum
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyutilib/enum/__init__.py", line 14, in <module>
    raise ImportError("""pyutilib.enum has been removed.
ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.
```

Does this sound familiar to you?

### LINKED ISSUE #157: jupyter single scenario nb fails with pandas>=1
```
TypeError                                 Traceback (most recent call last)
<ipython-input-44-4ff344a27c85> in <module>
----> 1 calc_dsm_cap(region=regions_scns[scenario])

~/git/WindNODE_ABW/windnode_abw/tools/draw.py in calc_dsm_cap(region, hh_share)
    857     dsm_cap_up = {ags:calc_dsm_cap_up(region.dsm_ts, ags,
    858                      mode=region.cfg['scn_data']['flexopt']['dsm']['params']['mode']) for ags in region.muns.index}
--> 859     df_dsm_cap_up = pd.DataFrame(dsm_cap_up).loc[region.cfg['date_from']:region.cfg['date_to']]
    860     df_dsm_cap_up = df_dsm_cap_up * hh_share
    861 

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
    878             maybe_callable = com.apply_if_callable(key, self.obj)
--> 879             return self._getitem_axis(maybe_callable, axis=axis)
    880 
    881     def _is_scalar_access(self, key: Tuple):

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1086         if isinstance(key, slice):
   1087             self._validate_key(key, axis)
-> 1088             return self._get_slice_axis(key, axis=axis)
   1089         elif com.is_bool_indexer(key):
   1090             return self._getbool_axis(key, axis=axis)

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexing.py in _get_slice_axis(self, slice_obj, axis)
   1120 
   1121         labels = obj._get_axis(axis)
-> 1122         indexer = labels.slice_indexer(
   1123             slice_obj.start, slice_obj.stop, slice_obj.step, kind="loc"
   1124         )

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py in slice_indexer(self, start, end, step, kind)
    716 
    717         try:
--> 718             return Index.slice_indexer(self, start, end, step, kind=kind)
    719         except KeyError:
    720             # For historical reasons DatetimeIndex by default supports

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexes/base.py in slice_indexer(self, start, end, step, kind)
   4958         slice(1, 3, None)
   4959         """
-> 4960         start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
   4961 
   4962         # return a slice

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexes/base.py in slice_locs(self, start, end, step, kind)
   5159         start_slice = None
   5160         if start is not None:
-> 5161             start_slice = self.get_slice_bound(start, "left", kind)
   5162         if start_slice is None:
   5163             start_slice = 0

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_slice_bound(self, label, side, kind)
   5071         # For datetime indices label may be a string that has to be converted
   5072         # to datetime boundary according to its resolution.
-> 5073         label = self._maybe_cast_slice_bound(label, side, kind)
   5074 
   5075         # we need to look up the label

~/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py in _maybe_cast_slice_bound(self, label, side, kind)
    661         if isinstance(label, str):
    662             freq = getattr(self, "freqstr", getattr(self, "inferred_freq", None))
--> 663             parsed, reso = parsing.parse_time_string(label, freq)
    664             reso = Resolution.from_attrname(reso)
    665             lower, upper = self._parsed_string_to_bounds(reso, parsed)

pandas/_libs/tslibs/parsing.pyx in pandas._libs.tslibs.parsing.parse_time_string()

TypeError: Expected unicode, got pandas._libs.properties.CachedProperty
```

Unluckily, docs tools planned to use features introduced in version 1.0. This should be changed to simply use tabulate directly for exporting `.rst` tables in #153 .

Apart from that `"pandas<1"` in setup.py fixes this issue.

### PR DESCRIPTION
**Pull request by gplssm**
Fix #78 
Fixes #157 
Fixes #125 

Updated docs https://windnode-abw.readthedocs.io/en/feature-78-display-notebooks-in-docs/

### CODE REVIEW

**Comment by gplssm** [comment]
I'm  done so far!
The final step would be to upload actual results notebooks to production instance of Zenodo (right now, sandbox.zenodo.org is used). I would do this, once we're happy with the presentation of results in general.

One question remains here: which timestamp should be used. Currently presented results come from `2020-08-18_101442_fixed`. is this correct?

Further optional changes

- sort scenarios with some logic
- Use `notebook_connected` renderer (interactive) for selected plots to enable hovering

**Review by nesnoj — CHANGES_REQUESTED** [review]
Hey, thanks for the nice integration!

Some comments from my end:
1. Timestamp: The latest is `2020-08-20_003243` which is to be used
2. Scenario order: Instead of using `os.listdir()`, you could use the scenario CSV as you did in the scenario table (only if it can be quickly done). To prevent including non-existing files I'd keep the current list and use the CSV's column to reorder..
3. In the docs' NB ([example](https://windnode-abw.readthedocs.io/en/feature-78-display-notebooks-in-docs/notebooks/scenario_analysis_ISE_RE-_AUT80_DSM%2B_BAT%2B_PTH%2B.html#0_scenario_information)) the TOC links do not work.

**Comment by gplssm** [comment]
Thanks for the feedback!

> Hey, thanks for the nice integration!
> 
> Some comments from my end:
> 
>     1. Timestamp: The latest is `2020-08-20_003243` which is to be used

Ok, I'll re-run with this timestamp.

>     2. Scenario order: Instead of using `os.listdir()`, you could use the scenario CSV as you did in the scenario table (only if it can be quickly done). To prevent including non-existing files I'd keep the current list and use the CSV's column to reorder..

Yes! I'll do this. For the scenario table I simply take the order defined in `scenarios.csv`. I'll do the same here. But therefore, I need to complete #140 before
 
>     3. In the docs' NB ([example](https://windnode-abw.readthedocs.io/en/feature-78-display-notebooks-in-docs/notebooks/scenario_analysis_ISE_RE-_AUT80_DSM%2B_BAT%2B_PTH%2B.html#0_scenario_information)) the TOC links do not work.

**Comment by gplssm** [comment]
Discussion with @nailend. Todos for @gplssm 

- [ ] Upload raw results to Zenodo
- [ ] Add link in single und multi NBs
- [ ] Create new executed notebooks
- [ ] Update deposit ID in `conf.py`
- [ ] Complete https://github.com/windnode/WindNODE_ABW/issues/78#issuecomment-664997533

**Comment by nesnoj** [comment]
Thank you @gplssm !! :rocket:

**Pull request merged**
