### PR TITLE
Feature/#132 dsm utilization

### LINKED ISSUE #132: DSM utilization
I started a seperate Issue for this on, as DSM potential is not yet extracted.

|# | Größe | Einheit | Plot/Tabelle | Kommentar | Done? |
|-------|----------|-----------|-----------------|-----------------|-----------------|
| D1 | DSM utilization relative to potential | % |  bar | x: ags, y: DSM utilization. Potential here refers to [flexibilizable demand](https://github.com/windnode/WindNODE_ABW/blob/57529661271779b785fed10570553d32417336bd/windnode_abw/model/region/model.py#L1498-L1502)  |  |

### PR DESCRIPTION
**Pull request by nailend**
Fixes #132

- dsm relative utilixation plot

### CODE REVIEW

**Comment by nesnoj** [comment]
Some notes
- Implementation looks correct
- You make use of the full DSM potential assuming a 100% DSM penetration of households, did I get this correctly?
In our scenarios just a share of hh are equipped with DSM tech (DSM param `hh_share` in cfg), shouldn't the numbers be in relation to the actual installed potential?
- What makes me curious in the new 8.3.4 plot: the picture 8.3.1 is not very clear concerning the up/down ratio, the new plot the values are very similar.
- We need some explaining notes on that plot but we can can do that for all plots later #130

**Comment by nailend** [comment]
Thx. Somehow i didnt send my comment yesterday night

**Comment by nailend** [comment]
>     * You make use of the full DSM potential assuming a 100% DSM penetration of households, did I get this correctly?
>       In our scenarios just a share of hh are equipped with DSM tech (DSM param `hh_share` in cfg), shouldn't the numbers be in relation to the actual installed potential?

I am not entirelly sure. It depends on what you want to say. In the single scenarios its probably better to include it and probably mention it in the plot title?

>     * What makes me curious in the new 8.3.4 plot: the picture 8.3.1 is not very clear concerning the up/down ratio, the new plot the values are very similar.
What do you mean by the up/down ratio? they seem a bit to similar but I couldnt find a problem. 
>     * We need some explaining notes on that plot but we can can do that for all plots later #130d
ok

**Comment by nesnoj** [comment]
To foster a better discussion, I've added it to the agenda for today's meeting..

**Pull request merged**
