### PR TITLE
Feature/#143 gen dem abw region

### LINKED ISSUE #143: generation and demand for entire ABW region in plot is missing

### PR DESCRIPTION
**Pull request by gplssm**
Fix #143 

Introduces two new plots in Section 4 of single scenario plots

### CODE REVIEW

**Comment by nesnoj** [comment]
No sorry, for the 2nd plot!

**Comment by gplssm** [comment]
> With `2020-08-07_061535` and `NEP2035` I'm getting for the first plot:
> 
> ```
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-20-b440760892c1> in <module>
>       3                    results_scns[scenario]['results_axlxt']['Wärmenachfrage nach Gemeinde'].sum()], index=idx) / 1e3
>       4 
> ----> 5 colors = [COLORS[c] for c in th.columns]
>       6 th = th.rename(columns=PRINT_NAMES)
>       7 
> 
> <ipython-input-20-b440760892c1> in <listcomp>(.0)
>       3                    results_scns[scenario]['results_axlxt']['Wärmenachfrage nach Gemeinde'].sum()], index=idx) / 1e3
>       4 
> ----> 5 colors = [COLORS[c] for c in th.columns]
>       6 th = th.rename(columns=PRINT_NAMES)
>       7 
> 
> KeyError: 'fuel_oil'
> ```

Classic! Just tested for 2050 scenarios...

**Comment by nesnoj** [comment]
Have u tested for SQ (and maybe other scenarios) too?

**Comment by gplssm** [comment]
> Have u tested for SQ (and maybe other scenarios) too?

Yes, at least StatusQuo_DSMno

This should be sufficient, right?

**Pull request merged**
